blog-site/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace blog_site.Controllers
{
    public class UploadController : Controller
    {
        // GET: Upload
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult UploadFile()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UploadFile(HttpPostedFileBase file)
        {
            try
            {
                if (file.ContentLength > 0)
                {
                    string _FileName = Path.GetFileName(file.FileName);
                    string _path = Path.Combine(Server.MapPath("~/UploadedFiles"), _FileName);
                    file.SaveAs(_path);
                }
                ViewBag.Message = "File Uploaded Successfully!!";
                return View();
            }
            catch
            {
                ViewBag.Message = "File upload failed!!";
                return View();
            }
        }
    }
}

blog-site/Views/Upload/UploadFile.cshtml
@{
    ViewBag.Title = "UploadFile";
}

<!-- Page Header-->
<header class="masthead" style="background-image: url('https://media.istockphoto.com/photos/cloud-computing-picture-id963131214?k=20&m=963131214&s=612x612&w=0&h=PFKzkJn0GTrdO-gS2fI14VFs-dR-fE6SIgJy_tEQR28=')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="page-heading">
                    <h1>Upload File</h1>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        @using (Html.BeginForm("UploadFile", "Upload", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div>
                @Html.TextBox("file", "", new { type = "file" }) <br />
                <input type="submit" value="Upload" />
                @ViewBag.Message
            </div>
        }
    </div>
</main>