blog-site/Controllers/BackendPostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using blog_site.Models;
using BlogBusinessLogic.Service;

namespace blog_site.Controllers
{
    public class BackendPostController : Controller
    {
        private PostService servicePost;
        private UserService serviceUser;

        public BackendPostController()
        {
            servicePost = new PostService(BlogBusinessLogic.Types.EnumFonte.Json);
            serviceUser = new UserService(BlogBusinessLogic.Types.EnumFonte.Json);
        }

        // GET: BackendPost

        public ActionResult List()
        {
            PostListModel model = new PostListModel();

            model.Posts = servicePost.GetAll().Select(oldModel => new PostModel()
            {
                PostId = oldModel.Id,
                Titolo = oldModel.Title,
                Contenuto = oldModel.Body,
                PostUser = serviceUser.GetAll().Where(x => x.Id == oldModel.UserId).Select(tmpUser => new UserModel()
                {
                    UserId = tmpUser.Id,
                    Nome = tmpUser.Name,
                    Username = tmpUser.Username,

                }).FirstOrDefault()
            }).ToList();

            return View(model);
        }

        public ActionResult Detail(int id)
        {
            PostDetailModel model = new PostDetailModel();

            model.Post = servicePost.GetAll().Where(x => x.Id == id).Select(tmpPost => new PostModel()
            {
                PostId = tmpPost.Id,
                Titolo = tmpPost.Title,
                Contenuto = tmpPost.Body,
                PostUser = new UserService().GetAll().Where(x => x.Id == tmpPost.UserId).Select(tmpUser => new UserModel()
                {
                    UserId = tmpUser.Id,
                    Nome = tmpUser.Name,
                    Username = tmpUser.Username

                }).FirstOrDefault()

            }).FirstOrDefault();

            return View(model);
        }

        public ActionResult Add()
        {
            BackendPostEditModel model = new BackendPostEditModel();


            return View("Edit",model);
        }

        public ActionResult Edit(int id)
        {
            BackendPostEditModel model = new BackendPostEditModel();

            var dbPost = servicePost.GetSinglePost(id);

            if (dbPost == null || dbPost.Id < 0) return RedirectToAction("List");

            model.Id = dbPost.Id;
            model.Title = dbPost.Title;
            model.Body = dbPost.Body;

            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SalvaPost(BackendPostEditModel model)
        {
            if (ModelState.IsValid)
            {

                return RedirectToAction("List");
            }

            return View("Edit", model);

            //salvo
            // new PostService().InserOrUpdate()


        }




        public ActionResult Delete(int id)
        {
            return View();
        }
    }
}

blog-site/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlogBusinessLogic.Models;
using BlogBusinessLogic.Service;
using blog_site.Models;

namespace blog_site.Controllers
{
    public class UserController : Controller
    {
        // GET: User

        private PostService servicePost;
        private UserService serviceUser;

        public UserController()
        {
            servicePost = new PostService(BlogBusinessLogic.Types.EnumFonte.WebService);
            serviceUser = new UserService(BlogBusinessLogic.Types.EnumFonte.WebService);
        }

        public ActionResult List()
        {
            //
            // CON SELECT
            //
            UserListModel model = new UserListModel();

            model.Users = serviceUser.GetAll().Select(oldModel => new UserModel()
            {
                UserId = oldModel.Id,
                Username = oldModel.Username,
                Nome = oldModel.Name

            }).ToList();

            return View(model);

            // ----------------------------------------------------------------------------------------
            //
            // CON IL FOREACH
            //
            // UserListModel model = new UserListModel();
            //
            //foreach (User user in new serviceUser.GetAll())
            //{
            //    List<Post> posts = new servicePost.GetAll();

            //    UserModel tmpModel = new UserModel();

            //    tmpModel.UserId = user.Id;
            //    tmpModel.Nome = user.Name;
            //    tmpModel.Username = user.Username;
            //    tmpModel.Email = user.Email;
            //    tmpModel.Posts = posts.Where(x => x.UserId == user.Id).Select(tmpPost => new PostModel()
            //        {
            //            UserId = tmpPost.UserId,
            //            Titolo = tmpPost.Title
            //        }).ToList();

            //    model.Users.Add(tmpModel);

            //}
            //
            // return View(model);
        }

        public ActionResult Detail(int id)
        {
            UserDetailModel model = new UserDetailModel();

            model.User = serviceUser.GetAll().Where(x => x.Id == id).Select(tmpUser => new UserModel()
            {
                UserId = tmpUser.Id,
                Nome = tmpUser.Name,
                Username = tmpUser.Username,
                Email = tmpUser.Email,
                Telefono = tmpUser.Phone,
                Sito = tmpUser.Website,
                Città = tmpUser.Address.City,
                Via = tmpUser.Address.Street,
                CodicePostale = tmpUser.Address.ZipCode

            }).FirstOrDefault();

            model.Posts = servicePost.GetAll().Where(x => x.UserId == id).Select(tmpPost => new PostModel()
            {
                PostId = tmpPost.id,
                UserId = tmpPost.UserId,
                Titolo = tmpPost.Title,
                Contenuto = tmpPost.Body

            }).ToList();

            return View(model);
        }
    }
}

blog-site/Views/Shared/_Footer.cshtml
@{
    ViewBag.Title = "_Footer";
}

<!-- Footer-->
<footer class="border-top">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
            </div>
        </div>
    </div>
</footer>

blog-site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>@ViewBag.Title | Mattia Blog</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="~/Content/css/styles.css" rel="stylesheet" />
    </head>
    <body>

        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link" href=@Url.Action("List", "BackendPost")>Tutti i Post</a></li>
                    <li class="nav-item"><a class="nav-link" href=@Url.Action("Add", "BackendPost")>Crea Post</a></li>
                </ul>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        @Html.Partial("~/Views/Shared/_NavBar.cshtml")
                    </ul>
                </div>
            </div>
        </nav>

        <div class="body-content">

            @RenderBody()

            @Html.Partial("~/Views/Shared/_Footer.cshtml")

        </div>

        <script src="~/Scripts/jquery-3.4.1.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
    </body>
</html>

blog-site/Views/Shared/_NavBar.cshtml
<li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href=@Url.Action("Index", "Home")>Home</a></li>
<li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href=@Url.Action("About", "Home")>About</a></li>
<li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href=@Url.Action("List", "User")>Users</a></li>
<li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href=@Url.Action("Contact", "Home")>Contact</a></li>