blog-site/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlogBusinessLogic.Models;
using BlogBusinessLogic.Service;
using blog_site.Models;

namespace blog_site.Controllers
{
    public class PostController : Controller
    {
        // GET: Post

        private PostService servicePost;
        private UserService serviceUser;

        public PostController()
        {
            servicePost = new PostService(BlogBusinessLogic.Types.EnumFonte.WebService);
            serviceUser = new UserService(BlogBusinessLogic.Types.EnumFonte.WebService);
        }

        public ActionResult List()
        {
            //
            // CON SELECT
            //
            PostListModel model = new PostListModel();

            model.Posts = servicePost.GetAll().Select(oldModel => new PostModel()
            {
                PostId = oldModel.id,
                Titolo = oldModel.Title,
                Contenuto = oldModel.Body,
                PostUser = serviceUser.GetAll().Where(x => x.Id == oldModel.UserId).Select(tmpUser => new UserModel()
                {
                    UserId = tmpUser.Id,
                    Nome = tmpUser.Name,
                    Username = tmpUser.Username,

                }).FirstOrDefault()

            }).ToList();

            return View(model);

            // ----------------------------------------------------------------------------------------
            //
            // CON IL FOREACH
            //
            // PostListModel model = new PostListModel();
            //
            //foreach (Post post in servicePost)
            //{
            //    User user = serviceUser.GetAll().FirstOrDefault(x => x.Id == post.UserId);

            //    PostModel tmpModel = new PostModel();

            //    tmpModel.PostId = post.Id;
            //    tmpModel.Titolo = post.Title;
            //    tmpModel.Contenuto = post.Body;
            //    tmpModel.UserId = post.UserId;

            //    model.Posts.Add(tmpModel);

            //}
            //
            // return View(model);
        }

        public ActionResult Detail(int id)
        {
            PostDetailModel model = new PostDetailModel();

            model.Post = servicePost.GetAll().Where(x => x.id == id).Select(tmpPost => new PostModel()
            {
                PostId = tmpPost.id,
                Titolo = tmpPost.Title,
                Contenuto = tmpPost.Body,
                PostUser = serviceUser.GetAll().Where(x => x.Id == tmpPost.UserId).Select(tmpUser => new UserModel()
                {
                    UserId = tmpUser.Id,
                    Nome = tmpUser.Name

                }).FirstOrDefault()

            }).FirstOrDefault();

            model.Comments = new CommentService().GetAll().FindAll(z => z.PostId == id);

            return View(model);
        }
    }
}

blog-site/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlogBusinessLogic.Models;
using BlogBusinessLogic.Service;
using blog_site.Models;

namespace blog_site.Controllers
{
    public class UserController : Controller
    {
        // GET: User

        private PostService servicePost;
        private UserService serviceUser;

        public UserController()
        {
            servicePost = new PostService(BlogBusinessLogic.Types.EnumFonte.WebService);
            serviceUser = new UserService(BlogBusinessLogic.Types.EnumFonte.WebService);
        }

        public ActionResult List()
        {
            //
            // CON SELECT
            //
            UserListModel model = new UserListModel();

            model.Users = serviceUser.GetAll().Select(oldModel => new UserModel()
            {
                UserId = oldModel.Id,
                Username = oldModel.Username,
                Nome = oldModel.Name

            }).ToList();

            return View(model);

            // ----------------------------------------------------------------------------------------
            //
            // CON IL FOREACH
            //
            // UserListModel model = new UserListModel();
            //
            //foreach (User user in new serviceUser.GetAll())
            //{
            //    List<Post> posts = new servicePost.GetAll();

            //    UserModel tmpModel = new UserModel();

            //    tmpModel.UserId = user.Id;
            //    tmpModel.Nome = user.Name;
            //    tmpModel.Username = user.Username;
            //    tmpModel.Email = user.Email;
            //    tmpModel.Posts = posts.Where(x => x.UserId == user.Id).Select(tmpPost => new PostModel()
            //        {
            //            UserId = tmpPost.UserId,
            //            Titolo = tmpPost.Title
            //        }).ToList();

            //    model.Users.Add(tmpModel);

            //}
            //
            // return View(model);
        }

        public ActionResult Detail(int id)
        {
            UserDetailModel model = new UserDetailModel();

            model.User = serviceUser.GetAll().Where(x => x.Id == id).Select(tmpUser => new UserModel()
            {
                UserId = tmpUser.Id,
                Nome = tmpUser.Name,
                Username = tmpUser.Username,
                Email = tmpUser.Email,
                Telefono = tmpUser.Phone,
                Sito = tmpUser.Website,
                Città = tmpUser.Address.City,
                Via = tmpUser.Address.Street,
                CodicePostale = tmpUser.Address.ZipCode

            }).FirstOrDefault();

            model.Posts = servicePost.GetAll().Where(x => x.UserId == id).Select(tmpPost => new PostModel()
            {
                PostId = tmpPost.id,
                UserId = tmpPost.UserId,
                Titolo = tmpPost.Title,
                Contenuto = tmpPost.Body

            }).ToList();

            return View(model);
        }
    }
}

blog-site/Views/Post/Detail.cshtml
@model blog_site.Models.PostDetailModel

@{
    ViewBag.Title = "Detail";
}

<!-- Page Header-->
<header class="masthead" style="background-image: url('https://picsum.photos/640/360') ">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="post-heading">
                    <h1 class="text-capitalize">@Model.Post.Titolo</h1>
                    <span class="meta">Scritto da <a href=@Url.Action("Detail", "User", new {id = Model.Post.PostUser.UserId })>@Model.Post.PostUser.Nome</a></span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Post Content-->
<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <h3>Testo:</h3>
            </div>
        </div>
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7 text-capitalize">
                <p>@Model.Post.Contenuto</p>
                <hr />
            </div>
        </div>
    </div>
</article>

<!-- Commenti -->
<div class="container px-4 px-lg-5">

    <div class="row justify-content-center mb-3">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <h5>Commenti:</h5>
        </div>
    </div>

    <div class="row gx-4 gx-lg-5 justify-content-center" style="font-size: 17px;">
        @foreach (var comment in Model.Comments)
        {
            <div class="col-md-10 col-lg-8 col-xl-7 mb-4">
                <span class="text-capitalize"><em><b>@comment.Name</b></em></span>
                <p class="text-capitalize text-secondary" style="padding: 0; margin: 0;"><em>@comment.Body</em></p>
                <span style="font-size: 15px;">da: @comment.Email</span>
            </div>
        }
    </div>

</div>

blog-site/Views/Post/List.cshtml
@model blog_site.Models.PostListModel

@{
    ViewBag.Title = "List";
}

<!-- Page Header-->
<header class="masthead" style="background-image: url('/Content/assets/img/home-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Clean Blog</h1>
                    <span class="subheading">A Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">

            <!-- Post List-->
            @foreach (var post in Model.Posts)
            {
                @Html.Partial("SinglePost", post)
            }

            <!-- Pager-->
            <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>

        </div>
    </div>
</div>

blog-site/Views/Post/SinglePost.cshtml
@model blog_site.Models.PostModel

<!-- Post preview-->
<div class="post-preview">
    <h3 class="post-title text-capitalize">@Model.Titolo</h3>
    <div class="post-subtitle"><a href=@Url.Action("Detail", "Post", new { id = Model.PostId})>Leggi l'articolo</a></div>
</div>
<!-- Divider-->
<hr class="my-4" />